apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: labour-hiring-system
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30080
  type: NodePort

