apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: labour-hiring-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image:  irfan845/labour-hiring-system-backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config

