apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: labour-hiring-system
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
    nodePort: 30081
  type: NodePort

