apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: labour-hiring-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: irfan845/labour-hiring-system-frontend:latest 
        ports:
        - containerPort: 80

