apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: labour-hiring-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: irfan845/labour-hiring-system-mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongo-persistent-storage
      volumes:
      - name: mongo-persistent-storage
        emptyDir: {}

